spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ashokitschool/configuration_properties
          default-label: main
          clone-on-start: true

management:
  security:
    enabled: false